// MTG community card nicknames → real Scryfall card names.
// Sourced from https://mtg.fandom.com/wiki/List_of_Magic_slang/Card_nicknames
// Add new entries here — keys must be lowercase.
const CARD_NICKNAMES = {
  'academy':      'Tolarian Academy',
  'ak':           'Ancestral Recall',
  'ancestral':    'Ancestral Recall',
  'bbe':          'Bloodbraid Elf',
  'beb':          'Blue Elemental Blast',
  'big blue':     'Morphling',
  'bob':          'Dark Confidant',
  'bolt':         'Lightning Bolt',
  'banana':       'Birds of Paradise',
  'birds':        'Birds of Paradise',
  'baby jace':    "Jace, Vryn's Prodigy",
  'balance':      'Balance',
  "cap'n tickles": "Captain's Claws",
  'cat jesus':    "Ajani's Pridemate",
  'chimney pimp': 'Chimney Imp',
  'clique':       'Vendilion Clique',
  'coco':         'Collected Company',
  'darcy':        "Dragon's Rage Channeler",
  'deed':         'Pernicious Deed',
  'delver':       'Delver of Secrets',
  'dr. teeth':    'Psychatog',
  'dr teeth':     'Psychatog',
  'e wit':        'Eternal Witness',
  'ewit':         'Eternal Witness',
  'e-wit':        'Eternal Witness',
  'ecd':          'Elspeth Conquers Death',
  'emmy':         'Emrakul, the Aeons Torn',
  'finks':        'Kitchen Finks',
  'fish':         'Mulldrifter',
  'gary':         'Gray Merchant of Asphodel',
  'goyf':         'Tarmogoyf',
  'grist':        'Grist, the Hunger Tide',
  'hippy':        'Hypnotic Specter',
  'hymn':         'Hymn to Tourach',
  'jace':         'Jace, the Mind Sculptor',
  'jtms':         'Jace, the Mind Sculptor',
  'jens':         'Solemn Simulacrum',
  'k command':    "Kolaghan's Command",
  'kcommand':     "Kolaghan's Command",
  'larry':        'Llanowar Elves',
  'lili':         'Liliana of the Veil',
  'lotv':         'Liliana of the Veil',
  'lili last hope': 'Liliana, the Last Hope',
  'lolth':        'Lolth, Spider Queen',
  'mike':         'Mikaeus, the Unhallowed',
  'mom':          'Mother of Runes',
  'moti':         'Morphling',
  'mox monkey':   'Gorilla Shaman',
  'necro':        'Necropotence',
  'niv':          'Niv-Mizzet, Parun',
  'panharmommycon': 'Panharmonicon',
  'path':         'Path to Exile',
  'plow':         'Swords to Plowshares',
  'prime time':   'Primeval Titan',
  'rhino':        'Siege Rhino',
  'reb':          'Red Elemental Blast',
  'sac elder':    'Sakura-Tribe Elder',
  'sad robot':    'Solemn Simulacrum',
  'scooze':       'Scavenging Ooze',
  'sfm':          'Stoneforge Mystic',
  'snap':         'Snapcaster Mage',
  'snappy':       'Snapcaster Mage',
  'snappie':      'Snapcaster Mage',
  'sofi':         'Sword of Fire and Ice',
  'steve':        'Sakura-Tribe Elder',
  'stplow':       'Swords to Plowshares',
  'swords':       'Swords to Plowshares',
  'superman':     'Morphling',
  't3feri':       'Teferi, Time Raveler',
  'teferi3':      'Teferi, Time Raveler',
  'thalia':       'Thalia, Guardian of Thraben',
  'thoracle':     "Thassa's Oracle",
  'tim':          'Prodigal Sorcerer',
  'titan':        'Primeval Titan',
  'tog':          'Psychatog',
  'top':          "Sensei's Divining Top",
  'trike':        'Triskelion',
  'ugin':         'Ugin, the Spirit Dragon',
  'vic':          'Vampire Nighthawk',
  'welder':       'Goblin Welder',
  'wog':          'Wrath of God',
  'yawgwin':      "Yawgmoth's Will",
  'young peezy':  'Young Pyromancer',
};

function resolveNickname(name) {
  return CARD_NICKNAMES[name.toLowerCase().trim()] || name;
}
